# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d7a3a2fce22880c7ef339e223d6fbac3da1826cebcdd66fd526be3c9da9df19b63da8492f446a4d0b45406057fd38e4d2718fef0432af36a83d9a8ddbc6744

test:
  secret_key_base: b13fa02ea28d9368570c25c4eafc6af7429a09719d0d71ccd5c9a073b700acedc99ecb3aa543de171cb419c0d94590c422bacccac9db10710cf7ec3984b7d5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
